services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=notiboard'
      - 'MYSQL_PASSWORD=admin123'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=notiboard'
    ports:
      - 33306:3306
  minio:
    image: minio/minio:latest
    volumes:
      - ./minio/:/data
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: always
    shm_size: '1gb'
    ports:
      - "9000:9000"
      - "9001:9001"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379