services:
  mysql:
    image: 'mysql:latest'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=notiboard'
      - 'MYSQL_PASSWORD=admin123'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=notiboard'
    ports:
      - 33306:3306
